# Generated by Django 3.1.2 on 2021-12-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('photo', models.CharField(max_length=255, verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, verbose_name='DNI')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('address', models.CharField(max_length=150, verbose_name='Dirección')),
                ('birthDate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('dischargeDate', models.DateField(verbose_name='Fecha de alta')),
                ('active', models.IntegerField(verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='Nombre de Usuario')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('level', models.IntegerField(verbose_name='Nivel')),
                ('initDate', models.DateField(verbose_name='Fecha de inicio')),
                ('finDate', models.DateField(verbose_name='Fecha de finalización')),
                ('report', models.CharField(max_length=255, verbose_name='Informe final')),
                ('idEmployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.category', verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentDate', models.DateField(verbose_name='Fecha de inscripción')),
                ('role', models.CharField(max_length=100, verbose_name='Rol')),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.client', verbose_name='Cliente')),
                ('idProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.project', verbose_name='Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, verbose_name='DNI')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('address', models.CharField(max_length=150, verbose_name='Direccion')),
                ('biography', models.CharField(max_length=255, verbose_name='Biografía')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.user', verbose_name='Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.user', verbose_name='Usuario'),
        ),
    ]
