# Generated by Django 3.1.2 on 2022-02-17 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dischargeDate',
            field=models.DateField(default=datetime.date(2022, 2, 17), verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='project',
            name='report',
            field=models.CharField(max_length=255, null=True, verbose_name='Informe final'),
        ),
    ]
