# Generated by Django 3.1.2 on 2022-01-21 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.FileField(upload_to='media/cat', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dischargeDate',
            field=models.DateField(default=datetime.date(2022, 1, 21), verbose_name='Fecha de alta'),
        ),
    ]
