# Generated by Django 3.1.2 on 2022-01-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20220121_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.FileField(upload_to='cat/', verbose_name='Foto'),
        ),
    ]
