# Generated by Django 3.1.2 on 2022-01-23 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20220121_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dischargeDate',
            field=models.DateField(default=datetime.date(2022, 1, 23), verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finDate',
            field=models.DateField(default='0001-01-01', verbose_name='Fecha de finalización'),
        ),
    ]
