# Generated by Django 3.1.2 on 2022-02-01 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_auto_20220127_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dischargeDate',
            field=models.DateField(default=datetime.date(2022, 2, 1), verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='participate',
            name='role',
            field=models.CharField(max_length=100, null=True, verbose_name='Rol'),
        ),
    ]
